#.
#Greater the number is, longer a recipe will take to craft
#Range: > 1
crafterProgressNeeded = 100
#.
#Greater the number is, faster a recipe will take to craft with high su
#Range: 1 ~ 56
speedRatio = 24
#.
#The stress impact of the Smart Crafter
#Range: > 1
crafterStressImpact = 5

